export const GET_ORDERLIST = "GET_ORDERLIST";
export const GET_CUSTOMERLIST = "GET_CUSTOMERLIST";
export const GET_EMPLOYEELIST = "GET_EMPLOYEELIST";
export const GET_PRODUCTLIST = "GET_PRODUCTLIST";
export const GET_TODOLIST = "GET_TODOLIST";
